In [1]:
import numpy as np

In [2]:
a = np.array([(1,2,3),(1,2,3)])

In [3]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [4]:
b = np.zeros([2,3])

In [5]:
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
c = np.ones([3,2])

In [7]:
c

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
c = np.reshape(c,(2,-1))

In [11]:
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
d = np.concatenate((b,c),axis = 0)
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
e = np.concatenate((b,c),axis = 1)
e

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [17]:
f = np.concatenate((b,c))
f

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
g = np.mean(a)
g

2.0

In [20]:
h = np.mean(a,axis=0)
h

array([1., 2., 3.])

In [21]:
i = np.mean(a,axis=1)
i

array([2., 2.])

In [50]:
j = np.sum(a,axis=0)
j

array([2, 4, 6])

In [52]:
arr = np.array([[6,3,1,9],[2,8,5,11]])

In [58]:
np.min(arr,axis=0)

array([2, 3, 1, 9])

In [59]:
np.min(arr,axis=1)

array([1, 2])

In [60]:
np.max(arr,axis=0)

array([ 6,  8,  5, 11])

In [61]:
np.max(arr,axis=1)

array([ 9, 11])

In [62]:
np.argmax(arr)

7

In [63]:
np.argmax(arr,axis=0)

array([0, 1, 1, 1], dtype=int64)

In [64]:
np.argmax(arr,axis=1)

array([3, 3], dtype=int64)

In [65]:
np.argmin(arr)

2

In [66]:
np.argmin(arr,axis=0)

array([1, 0, 0, 0], dtype=int64)

In [67]:
np.argmin(arr,axis=1)

array([2, 0], dtype=int64)

In [73]:
k = np.random.rand(2,3)
k

array([[0.01728329, 0.10775295, 0.20596898],
       [0.88545496, 0.13282346, 0.39392603]])

In [74]:
l = np.random.randn(2,3)
l

array([[-0.19535322, -0.74955668,  0.63186631],
       [-1.16128476, -0.43625158,  1.02632342]])

In [79]:
m = np.random.randint(0,1000)
m

972

In [82]:
l = np.reshape(l,(3,-1))
n = np.dot(k,l)
n

array([[-0.02514518,  0.07330412],
       [-0.26090066, -0.41364903]])